### ISSUE TITLE
How to fix the errors in the sources from https://github.com/bluebossa63/openstack-java-sdk/

### ISSUE THREAD

**Issue by twlkyao** [bluebossa63/OpenStackIntegration#1]
I have download the sources from https://github.com/bluebossa63/openstack-java-sdk/, but with some error on the pom.xml file for each project, I wonder how to fix the error, the error message is something like this:

> Failure to transfer org.sonatype.forge:forge-parent:pom:5 from http://repo.maven.apache.org/maven2 was cached in the 
>  local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. 
>  Original error: Could not transfer artifact org.sonatype.forge:forge-parent:pom:5 from/to central (http://
>  repo.maven.apache.org/maven2): No response received after 60000  

and my pom.xml file in `openstack-client` is like this:

> `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
>     <parent>
>         <groupId>com.woorea</groupId>
>         <artifactId>openstack-java-sdk</artifactId>
>         <version>3.2.2-SNAPSHOT</version>
>     </parent>
>     <artifactId>openstack-client</artifactId>
>     <name>OpenStack Client</name>
>     <description>OpenStack Client</description>
> </project>`

I am new to maven, thanks in advance.

**Comment by f2brossi** [comment]
Hello,

Difficult to say without knowing the IDE your are using. Try to import the
project as a maven project in Eclipse. that is what I am using with this
project.

Regards,

frédéric rossi

Try

1.Right click the project

2.Goto Maven

3.Click the "Update Project"

2014-06-03 16:57 GMT+02:00 Shiyao Qi notifications@github.com:

**Comment by twlkyao** [comment]
I am using Eclipse too, does I have to import the whole openstack-java-sdk project? I just want the needed modules.

**Comment by bluebossa63** [comment]
You have to build the openstack-java-sdk first with maven, then you have to add the needed modules to the eclipse project and mark them as exportable. I will add some hints to the docs today, stay tuned.

**Comment by bluebossa63** [comment]
I have added some pictures to the docs, please checkout the start page of the project.

You're maven error says that you could not access http://repo1.maven.org/maven2/org/sonatype/forge/forge-parent/5/forge-parent-5.pom
and I am not sure if you have access to the internet at all. If you are behind firewalls be sure to add a proxy to your maven settings file.

http://maven.apache.org/guides/mini/guide-proxies.html

I will setup the whole projects properly with maven on jenkins and nexus in 2-3 weeks as I plan to work more on the project during summer. I am currently involved in the last phase of a project and have to complete the work first to have enough room for something new.

If you're planning to even contribute to the project, please drop a mail.

I let this issue open as a call to improve the documentation ;-)

Just ask anything that is not clear for you in this thread. Maybe I will find the time to publish the parts of the mail conversation with frédéric that covers the same issues already. Sorry, I know, the project setup is very pragmatic.

**Comment by twlkyao** [comment]
@bluebossa63 I have successfully import the openstack-java-jdk project, I will give the steps that I am follwing from the very beginning:  
1. Checkout the openstack-java-jdk project.
2. Import the openstack-java-jdk project as a maven project into Eclipse.
3. Right click the openstack-java-jdk project and select **Run As** and then select **Maven clean**.
4. After step 3, all the sources under the openstack-java-jdk project will appear in the workspace at the same level with the openstack-java-jdk project.
5. Then configure the OpenStackIntegration project's build path as your pictures showing.

**Comment by mani2507** [comment]
@bluebossa63 Thanks for the clear explanation I have successfully imported Maven project and mapped into the Openstack android integration project, but it showing compile time error in two places, it's missing following class file in the given location 
com.woorea.openstack.swift.model.Objects,

swift model does have Object class only, but not Objects. Please help me out. I enclosed the screenshots as well. Thanks in Advance.
![error1](https://cloud.githubusercontent.com/assets/13732005/9173021/faff3b28-3f94-11e5-8d33-02436634a019.png)
![error2](https://cloud.githubusercontent.com/assets/13732005/9173022/fb038444-3f94-11e5-9a5a-1b2a9f58195b.png)

**Comment by bluebossa63** [comment]
Check out the patches here https://github.com/bluebossa63/openstack-java-sdk

**Comment by mani2507** [comment]
@bluebossa63 Thanks for the quick reply, will check and let you know.

**Comment by mani2507** [comment]
@bluebossa63 
Hi, Three are no patches found in the link provided, can you please explain a bit in detail as what should I do ? 

Thank you.

**Comment by bluebossa63** [comment]
https://github.com/bluebossa63/openstack-java-sdk/blob/master/swift-model/src/main/java/com/woorea/openstack/swift/model/Objects.java

You have to use the fork I made for this project...

**Comment by mani2507** [comment]
@bluebossa63 Thanks a a lot for the update, I have included the fork you have given, Now there is now compile time error, it successfully built. Thank you. 

But am getting the response as below snapshot when I try to register as new user, pls do the needful, Thanks once again.

![screenshot_2015-08-12-13-31-19](https://cloud.githubusercontent.com/assets/13732005/9219286/74780f80-40f7-11e5-8b07-118565ad3891.png)

![screenshot_2015-08-12-13-31-29](https://cloud.githubusercontent.com/assets/13732005/9219300/81beab22-40f7-11e5-8de0-cc0623995872.png)

**Comment by bluebossa63** [comment]
see https://github.com/bluebossa63/OpenStackIntegration/issues/5
