### ISSUE TITLE
project is imported as an Android Project in Eclipse with wrong JDK Compliance 1.5

### ISSUE THREAD

**Issue by f2brossi** [bluebossa63/OpenStackIntegration#2]
By default it seems that Eclipse use a wrong JDK Compliance  ( click Rigth on project Properties --> Java Compiler ) 1.5 that make the project in errors. 

By choosing 1.6, I have no more errors at compile time. 
However, trying to run the Application on my emulator I got a FATAL EXCEPTION when installing the apk:

Java.Lang.RuntimeException: Unable to instantiate activity : java.lang.ClassNotFoundException: Didn't find class TenantListViewActivity.

In fact, I don't remember if the project should be created as an Android project or a General Project.

**Comment by bluebossa63** [comment]
It is an Android project, using the android.jar as jvm base. That's why the jdk should not be added to the project.
ListViewActivity is a base class contained in the Android sdk.

**Comment by f2brossi** [comment]
Thx. It is exactly my pb.
I have lost my eclipse config after à reinstall that is why I have to
create again my project.
Evening
