### ISSUE TITLE
javax.net.SSL HandshakeExcepetion

### ISSUE THREAD

**Issue by rabaaBenelmabrouk** [bluebossa63/OpenStackIntegration#3]
when I try to login  I get 

![error](https://cloud.githubusercontent.com/assets/8303523/3855132/b91cecf8-1ee0-11e4-9160-27ff712158d9.png)

I change  DEFAULT_SIGNUP_URL = "https://openstack.niceneasy.ch:7443/account-management/rest/users/" with 
 DEFAULT_SIGNUP_URL = "https://172.168.10.5:7443/account-management/rest/users/";

**Comment by f2brossi** [comment]
It is better to define the hostname niceneasy.ch in your /etc/hosts file or
equivalent in windows.
But anyway after register , you Have to  confirm by email,is it the case ?

**Comment by rabaaBenelmabrouk** [comment]
the same error when I try to register

**Comment by f2brossi** [comment]
And you are using a  real device with android 4.4.2?

In fact the backend is managed by daniele ullrich.

**Comment by rabaaBenelmabrouk** [comment]
no  I use a virtual device

**Comment by f2brossi** [comment]
So am l until now .a nexus one with sdk 19.
Check that the backend is ok.that you can access the horizon login page for
sample.may be a  restart of the backend is needed .

I hope to have my backend running soon .

**Comment by bluebossa63** [comment]
I just restarted the jboss appserver, please retry... I think it was hung up somehow...

**Comment by rabaaBenelmabrouk** [comment]
![image](https://cloud.githubusercontent.com/assets/8303523/3868132/6c23b590-2024-11e4-988a-647d5c14d2f0.png)

**Comment by bluebossa63** [comment]
OK, seems I have to restart all openstack services. As I'm using devstack I'm not sure, if it will work without delay. Frédéric already told me, that with the new release (icehouse) some of the rest calls become incompatible...

**Comment by bluebossa63** [comment]
I'm restarting. Every already registered account will be gone, you will have to do the registering process again. Kill the application on android and delete the local data. The application is not prepared to deal with this kind of inconsistenices...

**Comment by bluebossa63** [comment]
OK, I stopped devstack by calling ./unstack.sh, did a sudo apt-get update / sudo apt-get dist-upgrade restarted the machine and started devstac by calling ./stack.sh. Everything was starting up like a charm.

I registered myself on my handset (Galaxy S4), shot a photo and uploaded it. Then I called

https://openstack.niceneasy.ch:7443

and choose project / objectstore / containers and selected the newly created folder, loaded the photograph down and saw my absolutely fresh face I always have on sunday mornings...

**Comment by f2brossi** [comment]
It is not possible to stay in havana with devstack?
It should

**Comment by bluebossa63** [comment]
I just stopped and started with ./unstack.sh and ./stack.sh and it works. 

And have a look at this documentation 

https://github.com/openstack-dev/devstack

it is possible to have a specific version checkout or started...

**Comment by f2brossi** [comment]
And so you are in icehouse now or still in havana?
I can not test today.
Authentification was not working on my devstack icehouse.

**Comment by bluebossa63** [comment]
I am on head of git master branch - so called unstable...

At the edge of technology..... scary...

**Comment by f2brossi** [comment]
Ok thx. I will test asap

**Comment by f2brossi** [comment]
Hello,
I have just installed the app on a wiko rainbow Android device 4.2.2. Low
cost device worth notice.
Login ok. I can debug also. But I have a slow connexion where i stay on
vacations.
Regards
Frederic
