### ISSUE TITLE
java.net.ConnectException

### ISSUE THREAD

**Issue by lakijer** [bluebossa63/OpenStackIntegration#5]
![register](https://cloud.githubusercontent.com/assets/13762180/9219818/db42cf58-40dd-11e5-88c0-dd7142238c85.png)

Why I can't register user? Url not good, or something else?

**Comment by bluebossa63** [comment]
No, that's my personal development server and it is simply not up an running ;-)

You can either try to setup the registration server part yourself: 
https://github.com/bluebossa63/openstack-server-apps

or wait for the weekend. If I have the time I will start up the server.
